### ISSUE TITLE
Adding the site title and Permalink

### ISSUE THREAD

**Issue by slin0013** [SSYC-WebTeam/SSYCmaster#10]
Site Title: 
Now: SEATTLE SINGLES YACHT CLUB
New: any suggests?

Permalink:
Now: Default use
New: any suggests?

**Comment by maureencrist** [comment]
Let’s discuss at class tonight. :-)

**Comment by JoshuaCharlesByrd** [comment]
Ok,

For sure, I will be there early and ready to code!

See you then,

J
      ^-----^
     |   OvO\
     |  ) :;;:( |
     | /  ....  |
  ===w=w===
