### ISSUE TITLE
#nav-footer - needs sub categories and icons on contact part

### ISSUE THREAD

**Issue by luisgamboa** [SSYC-WebTeam/SSYCmaster#13]
Work on creating the submenues

**Comment by JoshuaCharlesByrd** [comment]
Ok, Im working o it now!

**Comment by JoshuaCharlesByrd** [comment]
Hey, I tried to add the icons and address info under the contact menu in the footer. I can add an additional menu item but I can't add icons so I need some feedback on how to get this feature working.
