### ISSUE TITLE
breadcrumbs divider

### ISSUE THREAD

**Issue by luisgamboa** [SSYC-WebTeam/SSYCmaster#18]
Change the "»" between location for slash "/"

**Comment by slin0013** [comment]
I changed it, but it looks not really good. Please let me know if you have other ideas.

**Comment by luisgamboa** [comment]
Can you take an screenshot ? So I can have an idea of how it looks. Thanks

**Comment by slin0013** [comment]
I have sent screenshot by email. Also you can download the code from github. It will show on your local host too.
