### ISSUE TITLE
Slider Plugin

### ISSUE THREAD

**Issue by luisgamboa** [SSYC-WebTeam/SSYCmaster#27]
Add slider plugin front page

**Comment by luisgamboa** [comment]
Did you add the shortcut in the front page for the slider? I synced and the placeholder for the image is been replace by a shortcut : [metaslider id=146]
<img width="1440" alt="screen shot 2015-12-06 at 3 44 50 pm" src="https://cloud.githubusercontent.com/assets/13126219/11616452/4d3c72fa-9c30-11e5-938e-8fd91acf1175.png">

**Comment by maureencrist** [comment]
I didn’t.

**Comment by luisgamboa** [comment]
I backed up what I was working in before, but I synced first to pull anything new and then I noticed that. Maybe Josh is working in that.

**Comment by slin0013** [comment]
I didn't. I was working on other tasks.

**Comment by JoshuaCharlesByrd** [comment]
Yes,
 I was working on it. I ask Thomas question about it and when he got back
to me with an answer I forgot to change it back.

Josh

**Comment by JoshuaCharlesByrd** [comment]
got the plugin working but still configuring settings

**Comment by slin0013** [comment]
I just fixed meta slider plugin on my localhost, please upload on server. Also, please let me know if you have any comments.

![1](https://cloud.githubusercontent.com/assets/11307151/11774971/9eee7ee4-a1ef-11e5-8cd4-9dac1165991e.PNG)

**Comment by luisgamboa** [comment]
Awesome !

**Comment by JoshuaCharlesByrd** [comment]
Great job on that one!!!
