### ISSUE TITLE
Install plugins

### ISSUE THREAD

**Issue by JoshuaCharlesByrd** [SSYC-WebTeam/SSYCmaster#3]
Install plugins needed to achieve functionality requirements.

Home page slider
Dynamic calendar
Weather feed / RSS
Registration form
Contact form (contact from 7)
login for Skippers
Image Carousel
Photo Gallery
Backup buddy or free type
PHP manager
Search tool
anti-spam (akismet)
Permalink display
Updraft plus

**Comment by JoshuaCharlesByrd** [comment]
I noticed the assignee setting here and I would like to assign more than one team member but it will only allow one member for each issue.

**Comment by JoshuaCharlesByrd** [comment]
Help out if you have time! Add to the list or give some feedback.

So far I have tested and installed these plugins on my localhost...

Akismet - anti spam
Simple Slide show manager
responsive slider slideshow
Image Pro - an image resizing and media management for the users to manage image content
My Calendar
X Calendar Express
Contact form 7
US Weather widget - I like this one!
National Weather service alerts - this one integrates google map overlays
Updraft plus - backup and restoration plugin
Short codes Ultimate - for client use
All in one PHP 
PHP everywhere
WP Ultimate search
Custom registration form builder
MailChimp subscribe form
...

**Comment by JoshuaCharlesByrd** [comment]
Add some documentation of plugins!

**Comment by slin0013** [comment]
We discussed about plugins with the other designers at class. We have a list of plugins to work on it. I did that and upload on the server. Please check the wordpress dashboard on the host. Also if the project needs more plugins, please let me know. I will keep update.
