### ISSUE TITLE
Events content ?

### ISSUE THREAD

**Issue by luisgamboa** [SSYC-WebTeam/SSYCmaster#32]
Make sure events are being displayed

**Comment by slin0013** [comment]
I just made the 3 sub pages of event. Please let me know if you got any suggestions. Also I made the page orders in dashboard too.

**Comment by maureencrist** [comment]
I don't think we need any sub pages for events page. Josh is putting Upcoming Events plugin in sidebar and there is only one page of content.

**Comment by slin0013** [comment]
Okay, I moved out the sub pages for events.
