### ISSUE TITLE
client request for footer items

### ISSUE THREAD

**Issue by slin0013** [SSYC-WebTeam/SSYCmaster#37]
```
Drop the Twitter icon, keep FB and Instagram icons
Remove phone number (no office), main contact is the email address
```

**Comment by luisgamboa** [comment]
I added the two icons. What do you think guys?
<img width="1440" alt="screen shot 2015-12-06 at 3 05 22 pm" src="https://cloud.githubusercontent.com/assets/13126219/11616196/ee72e6dc-9c2a-11e5-94c6-3e28061ee04c.png">

**Comment by maureencrist** [comment]
LOVE the way you resolved the icons! Thank you!

**Comment by slin0013** [comment]
It looks really good.

**Comment by JoshuaCharlesByrd** [comment]
Ok,

I think the icons a cool, except the color of the Instagram icon.
