### ISSUE TITLE
Login widgets CSS

### ISSUE THREAD

**Issue by slin0013** [SSYC-WebTeam/SSYCmaster#39]
Login widgets needs the style

**Comment by slin0013** [comment]
I added the login widgets styles, it might need to adjust size... etc.

**Comment by luisgamboa** [comment]
I don't see any login form:
<img width="1438" alt="screen shot 2015-12-10 at 6 18 13 pm" src="https://cloud.githubusercontent.com/assets/13126219/11734272/6940ec78-9f6a-11e5-98f9-0adea8a11fe3.png">
