### ISSUE TITLE
calendar page

### ISSUE THREAD

**Issue by slin0013** [SSYC-WebTeam/SSYCmaster#45]
about calendar page, would you like to have a blank of sidebar area or expand it like as a calendar?

![2](https://cloud.githubusercontent.com/assets/11307151/11737583/6c45386e-9f8f-11e5-94f8-19680fc0e1b4.PNG)

![1](https://cloud.githubusercontent.com/assets/11307151/11737641/2d314022-9f90-11e5-9571-44160118a3a2.PNG)

**Comment by maureencrist** [comment]
Leave the calendar page as it is. Josh is making the upcoming events plugin display in the sidebar primary for the calendar page, and the events page. Please leave all formatting as it is.

**Comment by slin0013** [comment]
Ok, Thank you for letting me know.
