### ISSUE TITLE
login styling

### ISSUE THREAD

**Issue by luisgamboa** [SSYC-WebTeam/SSYCmaster#46]
add styling to login form

**Comment by luisgamboa** [comment]
I added the styling but Im having some issues with the header and the overflow:
<img width="1440" alt="screen shot 2015-12-13 at 6 16 39 pm" src="https://cloud.githubusercontent.com/assets/13126219/11771502/303e593e-a1c6-11e5-8ef6-d76a043384a2.png">
Because of the overflow is hidden it will display the login inside. 
<img width="1440" alt="screen shot 2015-12-13 at 6 16 46 pm" src="https://cloud.githubusercontent.com/assets/13126219/11771505/38aa20f8-a1c6-11e5-946d-aaf3a4a630e6.png">
<img width="1440" alt="screen shot 2015-12-13 at 6 16 57 pm" src="https://cloud.githubusercontent.com/assets/13126219/11771507/3d4cffe0-a1c6-11e5-8157-5aff4b9be6a0.png">
Also I notice that it will display login twice, it has to be hidden from the php. Because the one we want to display is the one displaying the user's name.

**Comment by slin0013** [comment]
I took out the Login, please check the pic. Also if you add new style, please upload to github.

![1](https://cloud.githubusercontent.com/assets/11307151/11772100/c4555422-a1cd-11e5-902d-b817ca4d2158.PNG)

**Comment by luisgamboa** [comment]
Perfect !

**Comment by luisgamboa** [comment]
Did you sync @slin0013 , I keep seen the login once I synced

**Comment by JoshuaCharlesByrd** [comment]
Yes,

I sync'd and checked the server and it looks good. Great job! Do you mean
your local host has a login bug? If it does I think it will be a css issue
on your localhost.

J

**Comment by slin0013** [comment]
Yes, I did sync, was just wondering why my login size and login button color looks different from yours.

**Comment by luisgamboa** [comment]
No idea I even deleted everything and downloaded again. :(
