### ISSUE TITLE
Install Meta Slider Plugin and Get It Working (PHP issue?)

### ISSUE THREAD

**Issue by maureencrist** [SSYC-WebTeam/SSYCmaster#8]
Meta Slider requires the GD or ImageMagick PHP extension. Please contact your hosting provider

**Comment by slin0013** [comment]
I uploaded "meta slider" on the server, but the photo upload only 2 MB. It takes time to work on the flexshow. I am not be able to login on the server now, so I couldn't check the ImageMagick yet. I will try to do at the class.

**Comment by maureencrist** [comment]
Great! Looking forward to seeing it at class tonight!

**Comment by slin0013** [comment]
I checked the Meta Slider Plugin on my local host before. It doesn't need to download other plugins. It looks good.
